-- ============================================================================
-- investor: SQLite schema
-- Single source of truth: state + audit trail + validation logs.
-- All timestamps are UTC ISO-8601 text.
-- ============================================================================

PRAGMA journal_mode = WAL;        -- readers never block the writer
PRAGMA busy_timeout = 5000;       -- wait up to 5 s on a lock instead of failing
PRAGMA foreign_keys = ON;
PRAGMA synchronous  = NORMAL;     -- durable with WAL, without the cost of FULL

-- ============================================================================
-- 1. CONFIGURATION
-- ============================================================================

-- Key/value runtime state (last rebalance dates, circuit-breaker flags, ...).
CREATE TABLE IF NOT EXISTS config (
    key         TEXT PRIMARY KEY,
    value       TEXT NOT NULL,            -- stored as text; the code casts
    updated_at  TEXT NOT NULL,
    note        TEXT
);

-- ============================================================================
-- 2. PORTFOLIO: TARGETS, POSITIONS, ORDERS, EQUITY
-- ============================================================================

-- Target weights per rebalance (allocator output).
CREATE TABLE IF NOT EXISTS target_weight (
    rebalance_id TEXT NOT NULL,           -- groups one rebalance
    ts           TEXT NOT NULL,
    symbol       TEXT NOT NULL,
    weight       REAL NOT NULL,
    reason       TEXT,                    -- why this symbol is in the target
    PRIMARY KEY (rebalance_id, symbol)
);

-- Live positions snapshot.
CREATE TABLE IF NOT EXISTS position (
    symbol        TEXT PRIMARY KEY,
    qty           REAL NOT NULL DEFAULT 0,
    avg_price     REAL,
    chandelier_stop REAL,                 -- stop level, if tracked locally
    updated_at    TEXT NOT NULL
);

-- Orders. client_order_id is the idempotency key (retries never duplicate).
CREATE TABLE IF NOT EXISTS order_log (
    client_order_id TEXT PRIMARY KEY,     -- generated by the robot ('inv-*')
    exchange_order_id TEXT,               -- id returned by the broker
    rebalance_id    TEXT,
    ts_created      TEXT NOT NULL,
    ts_updated      TEXT,
    symbol          TEXT NOT NULL,
    side            TEXT NOT NULL,        -- 'buy' | 'sell'
    type            TEXT NOT NULL,        -- 'market' | 'trailing_stop' ...
    qty             REAL NOT NULL,
    price           REAL,
    status          TEXT NOT NULL,        -- 'NEW'|'FILLED'|'CANCELED'|'REJECTED'|...
    filled_qty      REAL DEFAULT 0,
    avg_fill_price  REAL,
    fee             REAL DEFAULT 0,
    fee_asset       TEXT,
    retries         INTEGER DEFAULT 0,
    mode            TEXT NOT NULL,        -- 'DRY_RUN'|'PAPER'|'LIVE-REAL'; never mix environments
    raw_json        TEXT
);
CREATE INDEX IF NOT EXISTS idx_order_ts ON order_log(ts_created);
CREATE INDEX IF NOT EXISTS idx_order_status ON order_log(status);

-- Equity history, always mark-to-market, never cash balance: otherwise intraday drawdown
-- is understated and the drawdown cap is meaningless.
CREATE TABLE IF NOT EXISTS equity_history (
    ts            TEXT PRIMARY KEY,
    equity_mtm    REAL NOT NULL,          -- total value marked to market
    cash          REAL NOT NULL,
    peak          REAL NOT NULL,          -- reference for the circuit breaker
    drawdown      REAL NOT NULL,          -- (equity/peak)-1
    exposure      REAL NOT NULL,          -- long market value / equity
    regime        TEXT,
    source        TEXT NOT NULL DEFAULT 'mtm'
);

-- ============================================================================
-- 3. RATIONALE
-- ============================================================================

-- Explanation of each rebalance (deterministic markdown, optionally with AI prose).
CREATE TABLE IF NOT EXISTS ai_explanation (
    id            INTEGER PRIMARY KEY AUTOINCREMENT,
    ts            TEXT NOT NULL,
    rebalance_id  TEXT,                   -- the rebalance being explained
    summary       TEXT NOT NULL,          -- markdown shown on the dashboard
    model         TEXT,                   -- e.g. 'deepseek' or 'deterministic'
    inputs_json   TEXT,                   -- inputs, for reproducibility
    published     INTEGER NOT NULL DEFAULT 0
);

-- ============================================================================
-- 4. VALIDATION LOGS
-- ============================================================================

-- Structured application log.
CREATE TABLE IF NOT EXISTS app_log (
    id        INTEGER PRIMARY KEY AUTOINCREMENT,
    ts        TEXT NOT NULL,
    level     TEXT NOT NULL,              -- 'DEBUG'|'INFO'|'WARN'|'ERROR'|'CRITICAL'
    component TEXT NOT NULL,              -- 'orchestrator'|'circuit_breaker'|...
    message   TEXT NOT NULL,
    context_json TEXT                     -- state at the time, to reproduce the case
);
CREATE INDEX IF NOT EXISTS idx_log_ts    ON app_log(ts);
CREATE INDEX IF NOT EXISTS idx_log_level ON app_log(level);

-- Errors with full tracebacks, kept apart for quick review.
CREATE TABLE IF NOT EXISTS error_log (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    ts         TEXT NOT NULL,
    component  TEXT NOT NULL,
    error_type TEXT,
    message    TEXT NOT NULL,
    traceback  TEXT,
    resolved   INTEGER NOT NULL DEFAULT 0,
    note       TEXT
);
CREATE INDEX IF NOT EXISTS idx_error_ts ON error_log(ts);

-- Events worth a human look (anomalies, not errors), shown on the dashboard.
CREATE TABLE IF NOT EXISTS review_queue (
    id         INTEGER PRIMARY KEY AUTOINCREMENT,
    ts         TEXT NOT NULL,
    kind       TEXT NOT NULL,             -- 'cb_halt'|'cb_resume'|'stop_repaired'|...
    symbol     TEXT,
    detail     TEXT NOT NULL,
    severity   TEXT NOT NULL DEFAULT 'info',
    reviewed   INTEGER NOT NULL DEFAULT 0
);
CREATE INDEX IF NOT EXISTS idx_review_reviewed ON review_queue(reviewed);

-- Orchestrator heartbeat (watchdog). If it goes silent, the robot is down.
CREATE TABLE IF NOT EXISTS heartbeat (
    id           INTEGER PRIMARY KEY AUTOINCREMENT,
    ts           TEXT NOT NULL,
    cycle_type   TEXT NOT NULL,           -- 'heartbeat'
    status       TEXT NOT NULL,           -- 'ok' | 'skipped' | 'error'
    skip_reason  TEXT,                    -- e.g. 'equity_unreadable'
    duration_ms  INTEGER,
    equity_mtm   REAL
);
CREATE INDEX IF NOT EXISTS idx_heartbeat_ts ON heartbeat(ts);

-- ============================================================================
-- 5. VIEWS
-- ============================================================================

CREATE VIEW IF NOT EXISTS v_open_errors AS
SELECT ts, component, error_type, message
FROM error_log WHERE resolved = 0 ORDER BY ts DESC;

CREATE VIEW IF NOT EXISTS v_pending_review AS
SELECT ts, kind, symbol, severity, detail
FROM review_queue WHERE reviewed = 0 ORDER BY ts DESC;
